llm_config:    
  config_list:
      -  model: "Llama31-70B-Instruct"
         api_key: "sk-0WwLjWsBIi3jdzEenjeV-w"
         base_url: "https://hp3hebj84f.us-west-2.awsapprunner.com"
         max_retries: 3
         timeout: 30
